spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: ${JWT_SECRET}
    access-token-expired-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
    refresh-token-expired-time: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
    admin-access-token-expired-time: ${JWT_ADMIN_ACCESS_TOKEN_EXPIRED_TIME}
  redirect:
    front-end-url: ${FRONT_END_URL}
  oauth:
    password: ${OAUTH_PASSWORD}
    salt: ${OAUTH_SALT}
cors:
  origins: ${CORS_ORIGINS}
